MAIN_PAGE = "https://stellarburgers.nomoreparties.site/"
LOGIN_PAGE = MAIN_PAGE + "login"
REGISTER_PAGE = MAIN_PAGE + "register"
FORGOT_PASSWORD_PAGE = MAIN_PAGE + "forgot-password"
PROFILE_PAGE = MAIN_PAGE + "account/profile"